type: entities
entities:
  - entity: number.energy_planner_max_charge_current
    name: Laddningsström
  - entity: number.energy_planner_basic_nr_of_charge_hours
    name: Laddningstimmar
  - entity: number.energy_planner_basic_nr_of_discharge_hours
    name: Urladdningstimmar
  - entity: time.energy_planner_earliest_charge_time
    name: Första tillåtna laddningstid
  - entity: time.energy_planner_earliest_discharge_time
    name: Första tillåtna urladdningstid
