add_slot:
  name: Add Slot
  description: Add new slot, will overwrite part of or whole existing slots if they overlap
  fields:
    start:
      name: Start datetime
      description: Start datetime of the slot
      selector:
        datetime:
      required: true
    end:
      name: End datetime
      description: End datetime of the slot
      selector:
        datetime:
      required: true
    state:
      name: State
      description: State of the slot, one of 'charge', 'discharge', 'pause', 'sell', 'sell-excess', 'discard-excess', 'off'
      example: "discharge"
      required: true
      selector:
        select:
          options:
            - "charge",
            - "discharge",
            - "sell",
            - "sell-excess",
            - "discard-excess",
            - "pause",
            - "off",
    soc:
      name: SOC
      description: SOC for the slots
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: '%'
          mode: slider
run_planner:
  name: Run Planner
  description: Run the planner to calculate the schedule

clear_manual_slots:
  name: Clear Manual slots
  description: Clear the manual slots from the schedule
