add_slot:
  name: Add Slot
  description: Add new slot, will overwrite part of or whole existing slots if they overlap
  fields:
    start_time:
      name: Start time
      description: Start time of the slot
      example: "08:00"
      selector:
        time:
      required: true
    end_time:
      name: End time
      description: End time of the slot
      example: "16:00"
      selector:
        time:
      required: true
    start_date:
      name: Start date
      description: Date when the slot starts, it could end the next day if end time is before start time
      example: "2025-01-01"
      selector:
        date:
      required: true
    state:
      name: State
      description: State of the slot, one of 'charge', 'discharge', 'pause', 'off'
      example: "discharge"
      required: true
      selector:
        select:
          options:
            - "charge"
            - "discharge"
            - "pause"
            - "off"
run_planner:
  name: Run Planner
  description: Run the planner to calculate the schedule
