alias: Update battery action
description: ""
triggers:
  - trigger: time_pattern
    hours: /1
    minutes: /10
    seconds: "0"
  - trigger: state
    entity_id:
      - switch.energy_planner_slot_1_active
      - select.energy_planner_slot_1_state
      - select.energy_planner_slot_1_soc
      - datetime.energy_planner_slot_1_date_time_start
      - datetime.energy_planner_slot_2_date_time_start
  - trigger: numeric_state
    entity_id:
      - sensor.solis_s6_solis_meter_total_active_power
    above: 100
  - trigger: numeric_state
    entity_id:
      - sensor.solis_s6_solis_battery_discharge_power
    above: 500
conditions: []
actions:
  - action: python_script.update_battery_action
    metadata: {}
    data: {}
mode: single
